language: c

sudo: false

addons:
  apt:
    packages:
    - libgmp-dev

cache:
  directories:
    - $HOME/.stack

matrix:
  include:
  - env: ARGS="--resolver lts-8"
  - env: ARGS="--resolver lts-9"
  - env: ARGS="--resolver lts-10"
  - env: ARGS="--resolver lts-11"

before_install:
- unset CC
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script: stack $ARGS --no-terminal --install-ghc test --haddock --no-haddock-deps
